"""train_stations

Revision ID: da8ab5762d00
Revises: eaae517c1e2f
Create Date: 2021-03-28 15:27:24.481142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da8ab5762d00'
down_revision = 'eaae517c1e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_data',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('actual_arrival', sa.DateTime(), nullable=False),
    sa.Column('actual_departure', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_data_id'), 'daily_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_data_id'), table_name='daily_data')
    op.drop_table('daily_data')
    # ### end Alembic commands ###
