"""initialise

Revision ID: eaae517c1e2f
Revises: 
Create Date: 2021-03-22 12:32:07.701738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaae517c1e2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('expected_arrival_time', sa.Time(), nullable=False),
    sa.Column('expected_departure_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_id'), 'train', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_id'), table_name='train')
    op.drop_table('train')
    # ### end Alembic commands ###
